name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build main app
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create deployment structure
        run: |
          mkdir -p public-deploy
          cp -r dist/* public-deploy/
          mkdir -p public-deploy/storybook
          cp -r storybook-static/* public-deploy/storybook/
          
          # Create index.html that links to both apps
          cat > public-deploy/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Planetary Sim - Project Hub</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                      margin: 0;
                      padding: 0;
                      min-height: 100vh;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      display: flex;
                      align-items: center;
                      justify-content: center;
                  }
                  .container {
                      text-align: center;
                      background: white;
                      padding: 3rem;
                      border-radius: 20px;
                      box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                      max-width: 500px;
                      margin: 2rem;
                  }
                  h1 {
                      color: #333;
                      margin-bottom: 1rem;
                      font-size: 2.5rem;
                  }
                  p {
                      color: #666;
                      margin-bottom: 2rem;
                      font-size: 1.1rem;
                  }
                  .links {
                      display: flex;
                      gap: 1rem;
                      flex-direction: column;
                  }
                  .link-button {
                      display: inline-block;
                      padding: 1rem 2rem;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      text-decoration: none;
                      border-radius: 10px;
                      font-weight: 600;
                      transition: transform 0.2s ease, box-shadow 0.2s ease;
                  }
                  .link-button:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 10px 20px rgba(0,0,0,0.2);
                  }
                  .storybook-link {
                      background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%);
                  }
                  @media (min-width: 768px) {
                      .links {
                          flex-direction: row;
                          justify-content: center;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🪐 Planetary Sim</h1>
                  <p>Welcome to the Planetary Simulation project. Choose an application to explore:</p>
                  <div class="links">
                      <a href="./app.html" class="link-button">
                          🚀 Main Application
                      </a>
                      <a href="./storybook/" class="link-button storybook-link">
                          📚 Component Library
                      </a>
                  </div>
              </div>
          </body>
          </html>
          EOF
          
          # Rename the main app's index.html to app.html
          mv public-deploy/index.html public-deploy/app.html
          
          # Create the new index.html as the main landing page
          cat > public-deploy/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Planetary Sim - Project Hub</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                      margin: 0;
                      padding: 0;
                      min-height: 100vh;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      display: flex;
                      align-items: center;
                      justify-content: center;
                  }
                  .container {
                      text-align: center;
                      background: white;
                      padding: 3rem;
                      border-radius: 20px;
                      box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                      max-width: 500px;
                      margin: 2rem;
                  }
                  h1 {
                      color: #333;
                      margin-bottom: 1rem;
                      font-size: 2.5rem;
                  }
                  p {
                      color: #666;
                      margin-bottom: 2rem;
                      font-size: 1.1rem;
                  }
                  .links {
                      display: flex;
                      gap: 1rem;
                      flex-direction: column;
                  }
                  .link-button {
                      display: inline-block;
                      padding: 1rem 2rem;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      text-decoration: none;
                      border-radius: 10px;
                      font-weight: 600;
                      transition: transform 0.2s ease, box-shadow 0.2s ease;
                  }
                  .link-button:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 10px 20px rgba(0,0,0,0.2);
                  }
                  .storybook-link {
                      background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%);
                  }
                  @media (min-width: 768px) {
                      .links {
                          flex-direction: row;
                          justify-content: center;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🪐 Planetary Sim</h1>
                  <p>Welcome to the Planetary Simulation project. Choose an application to explore:</p>
                  <div class="links">
                      <a href="./app.html" class="link-button">
                          🚀 Main Application
                      </a>
                      <a href="./storybook/" class="link-button storybook-link">
                          📚 Component Library
                      </a>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public-deploy

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
